{% set name = "dargs" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/deepmodeling/dargs
  git_rev: v{{ version }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
    - setuptools_scm

  run:
    - python

test:
  imports:
    - dargs

about:
  home: https://github.com/deepmodeling/dargs
  #license: LGPL-3.0
  #license_family: LGPL
  #license_file: LICENSE
  doc_url: https://github.com/deepmodeling/dargs
  dev_url: https://github.com/deepmodeling/dargs

extra:
  recipe-maintainers:
    - njzjz
